[package]
name = "tui-app"
version = "0.1.0"
authors = ["Jerzy Wilczek <jerzywilczek@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
sysinfo = { version = "0.29.7", default-features = false }
tui = { package = "ratatui", version = "0.21.0" }
