[package]
name = "jtop"
version = "0.1.0"
authors = ["Jerzy Wilczek <jerzykwilczek@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
sysinfo = { version = "0.29.7", default-features = false }
tui = { package = "ratatui", version = "0.22.0" }
